### ISSUE TITLE
 information about the url parameter about open_url()

### ISSUE THREAD

**Issue by ZJur** [thaoshibe/edit-one-for-all#1]
Hello, I ran into a problem while trying to run your code.so I happen to be learning image processing and I came across this project and would like to learn more in depth, praying for your help!

Under edit-one-for-all-main\viz\renderer.py, 143, regarding open_url(), I would like to get more information about the url parameter needed for this call, is it a link to a model?

F:\anan\python.exe C:\Users\吴\PycharmProjects\edit\edit-one-for-all-main\my_gradio.py 
File under cache_dir (C:\Users\吴\PycharmProjects\edit\checkpoint):
['karras2019stylegan-ffhq-1024x1024.pkl', 'stylegan2-afhqcat-512x512.pkl']
Valid checkpoint file:
{'karras2019stylegan-ffhq-1024x1024': 'C:\\Users\\吴\\PycharmProjects\\edit\\checkpoint\\karras2019stylegan-ffhq-1024x1024.pkl', 'stylegan2-afhqcat-512x512': 'C:\\Users\\吴\\PycharmProjects\\edit\\checkpoint\\stylegan2-afhqcat-512x512.pkl'}
Loading "C:\Users\吴\PycharmProjects\edit\checkpoint\stylegan2-afhqcat-512x512.pkl"... Failed!
Traceback (most recent call last):
  File "C:\Users\吴\PycharmProjects\edit\edit-one-for-all-main\my_gradio.py", line 250, in <module>
    global_state = init_images(global_state)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\吴\PycharmProjects\edit\edit-one-for-all-main\my_gradio.py", line 70, in init_images
    state['renderer'].init_network(
  File "C:\Users\吴\PycharmProjects\edit\edit-one-for-all-main\viz\renderer.py", line 227, in init_network
    G = self.get_network(pkl, 'G_ema').to(self._device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\吴\PycharmProjects\edit\edit-one-for-all-main\viz\renderer.py", line 152, in get_network
    raise data
viz.renderer.CapturedException: Traceback (most recent call last):
  File "C:\Users\吴\PycharmProjects\edit\edit-one-for-all-main\viz\renderer.py", line 143, in get_network
    with dnnlib.util.open_url(pkl, verbose=False) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\吴\PycharmProjects\edit\edit-one-for-all-main\dnnlib\util.py", line 347, in open_url
    assert is_url(url)
AssertionError

**Comment by thaoshibe** [comment]
Hello @ZJur , sorry for the inconvenience.
The code right now is not completed yes, there's some components yet to be commited.
Thus, please stay tuned. I will try my best to commit latest code soon. Sorry!
